/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Pgm4Import } from './routes/pgm-4'
import { Route as Pgm3Import } from './routes/pgm-3'
import { Route as BacklogImport } from './routes/backlog'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsProjectIdImport } from './routes/projects/$projectId'

// Create/Update Routes

const Pgm4Route = Pgm4Import.update({
  id: '/pgm-4',
  path: '/pgm-4',
  getParentRoute: () => rootRoute,
} as any)

const Pgm3Route = Pgm3Import.update({
  id: '/pgm-3',
  path: '/pgm-3',
  getParentRoute: () => rootRoute,
} as any)

const BacklogRoute = BacklogImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogImport
      parentRoute: typeof rootRoute
    }
    '/pgm-3': {
      id: '/pgm-3'
      path: '/pgm-3'
      fullPath: '/pgm-3'
      preLoaderRoute: typeof Pgm3Import
      parentRoute: typeof rootRoute
    }
    '/pgm-4': {
      id: '/pgm-4'
      path: '/pgm-4'
      fullPath: '/pgm-4'
      preLoaderRoute: typeof Pgm4Import
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/pgm-3': typeof Pgm3Route
  '/pgm-4': typeof Pgm4Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/pgm-3': typeof Pgm3Route
  '/pgm-4': typeof Pgm4Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/pgm-3': typeof Pgm3Route
  '/pgm-4': typeof Pgm4Route
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog'
    | '/pgm-3'
    | '/pgm-4'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/backlog' | '/pgm-3' | '/pgm-4' | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backlog'
    | '/pgm-3'
    | '/pgm-4'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacklogRoute: typeof BacklogRoute
  Pgm3Route: typeof Pgm3Route
  Pgm4Route: typeof Pgm4Route
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacklogRoute: BacklogRoute,
  Pgm3Route: Pgm3Route,
  Pgm4Route: Pgm4Route,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/backlog",
        "/pgm-3",
        "/pgm-4",
        "/projects/$projectId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/backlog": {
      "filePath": "backlog.jsx"
    },
    "/pgm-3": {
      "filePath": "pgm-3.jsx"
    },
    "/pgm-4": {
      "filePath": "pgm-4.jsx"
    },
    "/projects/$projectId": {
      "filePath": "projects/$projectId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
